//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClsDatSysAgro
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenUsuarios
    {
        public int Id { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public string ImagenPerfil { get; set; }
        public string IDUnico { get; set; }
        public string TelefonoContacto { get; set; }
    }
}
