//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClsDatSysAgro
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenWatchDog
    {
        public int Id { get; set; }
        public string UsuarioSolicitud { get; set; }
        public string EmailSolicitud { get; set; }
        public string html { get; set; }
        public Nullable<bool> Enviado { get; set; }
        public Nullable<int> TipoEnvio { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
    }
}
